Пофанился
urfu-2017/markup-task-6 pull request #22
Opened 2017-11-20 22:06 UTC by Admirallll

2017-11-20 22:06 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-11-21 07:03 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-11-21 07:06 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-11-21 08:25 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-11-21 08:46 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-11-26 20:00 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-12-03 17:02 UTC, savichev-igor requested changes
Хорошо, но местами странные артефакты:
![image](https://user-images.githubusercontent.com/7279995/33527527-5748807c-d874-11e7-8336-7b39c3329575.png)
Причём некоторые переключатели вообще не работают.

Тут указал стрелочками на то, что не совпадает с макетом:
![image](https://user-images.githubusercontent.com/7279995/33527571-dc91b55a-d874-11e7-9e7a-7a593852b4ee.png)

![image](https://user-images.githubusercontent.com/7279995/33527610-a8fb455c-d875-11e7-9152-cabca1523c2b.png)

Если хочешь стать совсем крутым, то могу тебе порекомендовать вот такой [плагин](http://www.welldonecode.com/perfectpixel) для пиксель-перфект вёрстки.

А так молодец! Видно, что постарался.

🍅

2017-12-05 08:31 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-12-05 11:16 UTC, savichev-igor approved these changes

2017-12-05 11:16 UTC, Savichev-Igor commented
⭐️

2017-12-05 11:17 UTC, closed without merging