for review
urfu-2017/markup-task-6 pull request #3
Opened 2017-11-19 00:16 UTC by Morkhod

2017-11-19 00:17 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-11-19 18:51 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-11-20 16:44 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-11-20 20:38 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-11-28 21:48 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-12-01 08:43 UTC, savichev-igor requested changes
В целом молодец, но если хочешь быть совсем крутым, то поставь [плагин](http://www.welldonecode.com/perfectpixel/) и сможешь добить прямо как в макете всю вёрстку, ибо местами не совпадают те же отступы

2017-12-01 08:43 UTC, Savichev-Igor commented on index.css
> +    content: '◥';
Ну вообще не похожа иконка :<

2017-12-01 08:43 UTC, Savichev-Igor commented on index.css
> +    width: calc(92% - 85px);
Интересно

2017-12-01 08:43 UTC, Savichev-Igor commented on index.css
> +.auto-news-wrapper:after
У псевдоэлементов два `::` везде

2017-12-01 08:43 UTC, Savichev-Igor commented on index.html
> +    <div class="layout">
`div`'ов очень много :<

Погляди какие вообще есть тэги в HTML5+ и постарайся все заменить их на какие-то более семантичные

2017-12-01 08:43 UTC, Savichev-Igor commented on index.html
> +                        <span class="time">15:04</span>
Точно помню, что есть тэг `<time>` в спецификации

2017-12-01 08:43 UTC, Savichev-Igor commented on index.html
> +        <div class="main-box">
Контент не похож на `mail-box`

2017-12-01 08:43 UTC, Savichev-Igor commented on index.html
> +                <li class="news-item">В Кремле ответили на слова экс-главы ЦРУ о «запуганном»
А почему так странно вложил, почему не так?
```
<li>
    какой-то текст
</li>
```

2017-12-01 08:43 UTC, Savichev-Igor commented on index.html
> +                    --><input type="submit" class="search-button" value="Найти"><!--
Это у тебя комментарий или что?

`--><!--`

2017-12-01 08:43 UTC, Savichev-Igor commented on index.html
> +                <li class="visiting-item active">
Тоже какая-то странная вложенность

2017-12-01 17:56 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-12-03 16:20 UTC, Savichev-Igor commented
Молодец, выглядит круто!

Ещё бы поставил `min-width` какой-нибудь на `layout`, чтобы при масштабировании не разваливалось, а вело себя как на настоящей главной.

2017-12-03 16:20 UTC, savichev-igor approved these changes

2017-12-03 16:20 UTC, closed without merging