В процессе star
urfu-2017/markup-task-6 pull request #35
Opened 2017-11-21 09:55 UTC by Rolyx2

2017-11-21 09:56 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-11-21 09:59 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-11-21 12:53 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-11-27 09:23 UTC, Mokoshka requested changes
- Кнопка поехала куда-то, а баннер с рекламой хочется чтобы изменялся как и поисковая строка
![2017-11-27 14-10-09](https://user-images.githubusercontent.com/14892550/33259296-41826212-d37e-11e7-980c-edbd752024dd.png)
- Хочется стрелочку у кнопки "Найти"

2017-11-27 09:23 UTC, Mokoshka commented on index.css
> +    margin-top: 12px;
схлопнуть можно

2017-11-27 09:23 UTC, Mokoshka commented on index.html
> +                <label for="visited" class="set blue-title">Посещаемые</label><br>
Ну что за br, давай без него

2017-11-27 09:23 UTC, Mokoshka commented on index.html
> +            <div class="settings">
Не видно что выбрано а что нет, пользователи не обрадовались бы

2017-11-27 09:23 UTC, Mokoshka commented on index.html
> +                <p>Login<input type="search"></p>
Зачем input в p вставлять?

2017-11-27 09:23 UTC, Mokoshka commented on index.html
> +                <div class="firstJoke">
Зачем обертка в виде div?

2017-11-27 15:15 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-11-28 08:27 UTC, Mokoshka requested changes
Сейчас верстка выглядит вот так:
![2017-11-28 13 22 40](https://user-images.githubusercontent.com/14892550/33309311-8abcd78e-d43f-11e7-97d1-91b23027d23d.png)
![2017-11-28 13 20 47](https://user-images.githubusercontent.com/14892550/33309322-8eac0748-d43f-11e7-9f2f-5214bfbd8ca8.png)

А хочется вот так:
![2017-11-28 13 20 24](https://user-images.githubusercontent.com/14892550/33309329-964136d6-d43f-11e7-9559-9de2231e372e.png)
![2017-11-28 13 21 55](https://user-images.githubusercontent.com/14892550/33309336-9ace9df6-d43f-11e7-80db-7bdecf5cb765.png)
Попробуй воспользоваться флексами для этого

И чтобы кнопка не переносилась на маленьком экране
![2017-11-28 13-26-04](https://user-images.githubusercontent.com/14892550/33309357-b38a4f7a-d43f-11e7-9ab5-47096f0bed32.png)

2017-11-28 08:27 UTC, Mokoshka commented on index.css
> +    position: absolute;
Лучше сделать position: relative. Тогда кнопку будет проще позиционировать

2017-11-28 16:52 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-11-29 09:17 UTC, Mokoshka requested changes
- Тут вот маленький недочет
![2017-11-29 14 09 37](https://user-images.githubusercontent.com/14892550/33367312-e6a939cc-d50f-11e7-956d-5f2c2cabb69c.png)
- Давай добавим немного семантичности. Например, каждый блок ниже поисковой строки напоминает секцию

2017-11-29 09:17 UTC, Mokoshka commented on index.css
> +    display: table-cell;
Здесь же не нужен table-cell)

2017-11-29 09:17 UTC, Mokoshka commented on index.css
> +    width: 80%;
Киллер фича флексов. Когда ставишь width: 80%, то это значение надо будет менять в зависимости от соседних элементов и их ширины. А если там будет динамический контент?
У флексов есть замечательное свойство flex-grow, которое решает все проблемы с шириной элементов в одну строчку. Попробуй использовать его, вместо ширины у input.

2017-11-29 09:17 UTC, Mokoshka commented on index.css
> +    display: flex;
Здесь не нужен flex.
А еще раньше он очень круто находился в псевдо-элементе before.
Можно применить достаточно распространенный трюк: позиционировать :before абсолютно, а у основного элемента сделать margin-right равный ширине :before. Получится красиво и оптимизировано

2017-11-29 09:17 UTC, Mokoshka commented on index.css
> +    display: inline;
Зачем inline?

2017-11-29 09:17 UTC, Mokoshka commented on index.css
> +    box-sizing: border-box;
Эта строчка будет не нужна

2017-11-29 15:10 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-12-01 12:58 UTC, Mokoshka approved these changes

2017-12-01 12:58 UTC, closed without merging