done
urfu-2017/markup-task-6 pull request #38
Opened 2017-11-21 11:11 UTC by trszdev

2017-11-21 11:11 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-11-27 09:31 UTC, Mokoshka requested changes
- Не хватает семантики. Давай будем использовать различные article, section, заголовки у секций
- Не используй br. Все места где ты его используешь можно аккуратно и красиво исправить с помощью css.
- Не хватает стрелочки у кнопки "Найти"

2017-11-27 09:31 UTC, Mokoshka commented on index.css
> +    color: black;
Почему использовал название цвета, а не hex-код?

2017-11-27 09:31 UTC, Mokoshka commented on index.css
> +    object-fit: fit;
Что?

2017-11-27 09:31 UTC, Mokoshka commented on index.html
> +        <span class="yandex-color">login</span><br>
Давай без br

2017-11-27 09:31 UTC, Mokoshka commented on index.html
> +                <br>бесплатно и навсегда
И здесь без br

2017-11-27 09:31 UTC, Mokoshka commented on index.html
> +        <div class="searchbox">
Зачем две обертки-div?

2017-11-27 09:31 UTC, Mokoshka commented on index.html
> +                Раздел: <a href="#">Медицинские</a> . <br>
И здесь без br

2017-11-27 09:31 UTC, Mokoshka commented on index.html
> +                <br>
И здесь без br

2017-11-29 16:09 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-11-29 16:10 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-11-29 16:23 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-11-29 16:37 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-11-29 16:38 UTC, trszdev commented on index.css
> +    color: black;
2e1cf23

2017-11-29 16:38 UTC, trszdev commented on index.css
> +    object-fit: fit;
2e1cf23

2017-11-29 16:38 UTC, trszdev commented on index.html
> +        <span class="yandex-color">login</span><br>
2e1cf23

2017-11-29 16:38 UTC, trszdev commented on index.html
> +                <br>бесплатно и навсегда
2e1cf23

2017-11-29 16:38 UTC, trszdev commented on index.html
> +        <div class="searchbox">
2e1cf23

2017-11-29 16:39 UTC, trszdev commented on index.html
> +                Раздел: <a href="#">Медицинские</a> . <br>
2e1cf23

2017-11-29 16:39 UTC, trszdev commented on index.html
> +                <br>
2e1cf23

2017-12-01 13:05 UTC, Mokoshka requested changes

2017-12-01 13:05 UTC, Mokoshka commented on index.css
> +/* stylelint-disable */
🤔  так-так-так

2017-12-01 13:05 UTC, Mokoshka commented on index.css
> +    align-self: end;
Для чего это?

2017-12-01 13:05 UTC, Mokoshka commented on index.css
> +    display: inline-flex;
Почему именно inline-flex, а не flex?

2017-12-04 16:30 UTC, trszdev commented on index.css
> +/* stylelint-disable */
Я думал никто не узнает...)

2017-12-04 16:38 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-12-04 16:38 UTC, trszdev commented
Пора закрывать задачу

2017-12-11 06:20 UTC, Mokoshka approved these changes

2017-12-11 06:22 UTC, closed without merging