2
urfu-2017/markup-task-6 pull request #44
Opened 2017-11-21 12:25 UTC by strota

2017-11-21 12:25 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-11-21 12:28 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-11-21 12:29 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-11-21 12:30 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-11-21 12:35 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-11-21 12:38 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-11-21 12:42 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-11-21 12:47 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-11-21 12:50 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-11-21 12:51 UTC, strota commented
Я загрузила в 17:49

2017-11-26 14:09 UTC, f0rmat1k requested changes
Привет. Сори за задержку с фидбеком, я добавлю несколько дней к срокам.
Повторю, что звучит в задании:
> Как можно более точно соответствовать макету

Замечания:

![1](https://user-images.githubusercontent.com/769992/33240731-af9f969a-d2dc-11e7-9fe7-05e48f4d7c7c.png)

1. Я понимаю, что оригинальный блок довольно сложный по верстке, но давай хотя бы без иконок соц. сетей и с правильным цветом и размером шрифтов элементов. И это должны быть input'ы, а не что-то другое. Можно показать уже залогигенный блок, это проще.
2. Шрифт не тот
3. Не тот цвет ссылок, этот текст не должен быть жирным.
4. Не тот размер шрифта
5. Нет гор. отступов между блоками котировок, шрифт вроде чуть больше нужного.
6. Нет правого уголка у кнопки, не тот размер шрифта
7. Логотип совсем не похож. Стоит сделать его картинкой, можно взять прям с яндекса.
8. Строки совсем слиплись.

2017-11-26 14:15 UTC, f0rmat1k commented
2-я порция замечаний:
![2](https://user-images.githubusercontent.com/769992/33240791-bef523f2-d2dd-11e7-9852-faa168ee638b.png)

1. Цвет, жирность шрифта
2. Нет иконки
3. Нет иконки облака
4. кол-во градусов слиплось с заголовком
5. Между колонками нет отступа.
6. тут все должно быть в одну строку. Если текст не влазит, ставится `...`

2017-11-26 14:17 UTC, f0rmat1k commented
Еще отдельное замечание: нужно указать минимальную ширину. Сейчас все слишком слипается, если сузить окно браузера.

2017-11-28 12:25 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-11-28 12:43 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-11-28 17:20 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-11-28 19:37 UTC, closed without merging