Носов Андрей
urfu-2017/markup-task-6 pull request #52
Opened 2017-11-21 18:59 UTC by nosovandrew

[Посмотреть решение](https://rawgit.com/nosovandrew/markup-task-6/master/index.html)

2017-11-21 19:00 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-11-21 19:01 UTC, nosovandrew commented
@Savichev-Igor Я не оконца сделал, торопился из-за срока сдачи. Завтра все сделаю как положено.

2017-11-23 19:45 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2017-11-23 19:54 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-12-02 17:25 UTC, nosovandrew commented
@Savichev-Igor Привет! Ты не забыл про меня?) А еще я сдал 7 и 8 задачи

2017-12-05 11:35 UTC, savichev-igor requested changes
Контент находится не по центру на больших экранах:
![image](https://user-images.githubusercontent.com/7279995/33604617-7147633e-d9d8-11e7-986d-0750cc2b5e4e.png)

Местами несоответствия макету:
![image](https://user-images.githubusercontent.com/7279995/33605141-42c8e102-d9da-11e7-9919-77bd8f3e8fd9.png)

Если хочешь быть совсем крутым, то поставь вот этот [плагин](http://www.welldonecode.com/perfectpixel) и доведи всё до идеала

🍅

2017-12-05 11:35 UTC, savichev-igor commented on index.html
> +        <div class="topLeft">
Кажется, что где-то в гайдах было про то, что рекомендуется именовать классы через `-`, а не в `camelCase`

2017-12-05 11:35 UTC, savichev-igor commented on index.html
> +        </div>
Зачем выносить его на новую строку?

2017-12-05 11:35 UTC, Savichev-Igor commented on index.css
> +    color: gray;
Цвета лучше всегда задавать в `#hex`

2017-12-05 11:35 UTC, Savichev-Igor commented on index.css
> +    margin-right: 12px;
`margin: 4px 0 10px 12px`?

2017-12-05 11:35 UTC, Savichev-Igor commented on index.css
> +    margin-right: 12px;
Аналогично

2017-12-05 11:35 UTC, Savichev-Igor commented on index.css
> +    margin-left: 6px;
`margin: 0 6px;`?

2017-12-05 11:35 UTC, Savichev-Igor commented on index.css
> +    margin-bottom: 10px;
`margin: 9px 0 10px`?

2017-12-05 11:35 UTC, Savichev-Igor commented on index.css
> +/* .search-button::after
???

2017-12-05 11:35 UTC, Savichev-Igor commented on index.css
> +    margin-top: 4px;
Аналогично

2017-12-05 11:35 UTC, Savichev-Igor commented on index.css
> +    margin-left: 10px;
Аналогично

2017-12-05 11:35 UTC, Savichev-Igor commented on index.css
> +    margin-right: 8px;
Аналогично

2017-12-05 11:35 UTC, Savichev-Igor commented on index.css
> +    margin-top: 4px;
Аналогично

2017-12-05 11:35 UTC, Savichev-Igor commented on index.css
> +    margin-bottom: 10px;
...

2017-12-05 11:35 UTC, Savichev-Igor commented on index.css
> +    margin-top: 4px;
...

2017-12-05 11:35 UTC, Savichev-Igor commented on index.html
> +        <div class="topSettings">
Чего-то везде `div`'ы, где семантичная вёрстка?

2017-12-05 11:35 UTC, Savichev-Igor commented on index.html
> +                <a>Видео</a>
`href="#"`

2017-12-05 11:35 UTC, Savichev-Igor commented on index.html
> +                    <input class="search-main-input" type="text">
`type="text"` по-умолчанию, кажется

2017-12-05 17:12 UTC, nosovandrew commented on index.html
> +        <div class="topLeft">
Хорошо, я учту! Но можно я не буду все править?)

2017-12-05 17:16 UTC, nosovandrew commented on index.html
> +        <div class="topSettings">
Хорошо, я больше так не буду, просто увлекся немного)

2017-12-05 18:52 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-12-06 07:07 UTC, Savichev-Igor commented
На 13 дюймовом мониторе виден горизонтальный скролл, хотя если открыть главную Яндекса, то всё ок и места хватает:
![image](https://user-images.githubusercontent.com/7279995/33649021-0b3be1ea-da7e-11e7-8421-2aa8d57f324b.png)

2017-12-06 08:47 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-12-06 08:48 UTC, nosovandrew commented
@Savichev-Igor Постарался сделать небольшое сжатие крайних блоков, убрал фиксированную ширину

2017-12-06 11:01 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2017-12-06 11:01 UTC, nosovandrew commented
@Savichev-Igor Вроде бы сделал, посмотри)

2017-12-06 19:40 UTC, savichev-igor approved these changes

2017-12-06 19:40 UTC, closed without merging